name: meta-wepp-1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - snakemake=8.24.1
  - numpy
  - pandas
  - pip
  - cmake
  - cffi
  - coincbc
  - git
  - pyyaml
  - requests
  - dpath
  - attrs
  - click
  - jinja2
  - jsonschema
  - pytest
  - typing-extensions
  - mess=0.10.0
  - art
  - biopython
  - boto3
  - botocore
  - dropbox
  - seqkit
  - sra-tools
  - ncbi-datasets-cli
  - ncbi-vdb
  - google-api-python-client
  - google-cloud-storage
  - google-auth
  - cryptography
  - aiohttp
  - yarl
  - typer
  - typer-slim
  - typer-slim-standard
  - peppy
  - pephubclient
  - paramiko
  - smart_open
  - rich
  - eido
  - coloredlogs
  - pulp
  - tabulate
  - wheel
  - pip:
      - attrmap
      - rich-click
      - snaketool-utils
